/**
 * This file generated by Apso.
 */
import { CustomerModule } from './Customer/Customer.module';
import { ProductModule } from './Product/Product.module';
import { OrderModule } from './Order/Order.module';
import { OrderItemModule } from './OrderItem/OrderItem.module';

export default [CustomerModule, ProductModule, OrderModule, OrderItemModule];
